run:
  skip-files:
    - ready_test.go
linters:
  enable:
    - revive 
    - ifshort 
    - gocritic 
    - dogsled 
    - gosec 
    - misspell 
    - goconst 
    - goconst 
    - noctx 
    - godot

